version: '3'

services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - 9999:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    api:
        build: dapi
        image: tunix/dapi
    bot:
        build: dbot
        image: tunix/dbot
        links:
        #     - db
            - api
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            VIRTUAL_HOST: ${VIRTUALHOST}
            API_HOST: api
    # db:
    #     image: mysql
    #     environment:
    #         - MYSQL_ALLOW_EMPTY_PASSWORD=true
    #         - MYSQL_DATABASE=demo
    #         - MYSQL_USER=user
    #         - MYSQL_PASSWORD=test
