version: '3'

services:
    proxy:
        image: jwilder/nginx-proxy
        container_name: proxy
        ports:
            - 9999:80
        volumes:
            - /var/run/docker.sock:/tmp/docker.sock:ro
    api:
        build: dapi
        image: tunix/dapi
        links:
            - db
        environment:
            DB_HOST: db
        command: ["/source/wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/demo.jar"]
    bot:
        build: dbot
        image: tunix/dbot
        links:
            - api
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            VIRTUAL_HOST: ${VIRTUALHOST}
            API_HOST: api
    db:
        build: db
        image: tunix/db
