version: "3"

networks:
    demo:
        driver: overlay

services:
    api:
        image: tunix/docker-izmir-demo-api
        environment:
            DB_HOST: db
        command: ["/source/wait-for-it.sh", "db:3306", "--", "java", "-jar", "/app/demo.jar"]
        networks:
            - demo
        deploy:
            mode: global
            placement:
                constraints:
                    - engine.labels.role == node
    bot:
        image: tunix/docker-izmir-demo-bot
        environment:
            BOT_TOKEN: ${BOT_TOKEN}
            BOT_HOST: ${VIRTUALHOST}
            API_HOST: api
        networks:
            - demo
        ports:
            - 3000:3000
        deploy:
            mode: global
            placement:
                constraints:
                    - engine.labels.role == node
    db:
        image: tunix/docker-izmir-demo-db
        networks:
            - demo
        deploy:
            placement:
                constraints:
                    - engine.labels.role == db
